CREATE DATABASE identity_db;
CREATE DATABASE customer_db;
CREATE DATABASE kyc_db;
CREATE DATABASE wallet_db;
CREATE DATABASE transaction_db;
CREATE DATABASE ledger_db;

GRANT ALL PRIVILEGES ON DATABASE identity_db TO bastion;
GRANT ALL PRIVILEGES ON DATABASE customer_db TO bastion;
GRANT ALL PRIVILEGES ON DATABASE kyc_db TO bastion;
GRANT ALL PRIVILEGES ON DATABASE wallet_db TO bastion;
GRANT ALL PRIVILEGES ON DATABASE transaction_db TO bastion;
GRANT ALL PRIVILEGES ON DATABASE ledger_db TO bastion;