version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bastion_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bastion
      POSTGRES_PASSWORD: bastion_secret
      POSTGRES_DB: bastion_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init-databases.sql:/docker-entrypoint-initdb.d/01-init-databases.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bastion -d bastion_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bastion_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.2
    container_name: bastion_redpanda
    restart: unless-stopped
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  postgres_data:
  redpanda_data:
